version: '3'

services:
  shop_proxy:
    ports:
      - "6080:6080"

  shop_back:
    image: webdevops/php-dev:7.4-alpine
    depends_on:
      - shop_db
    ports:
     - "9003:9003"
    environment:
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHP_IDE_CONFIG

  shop_db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  shop_redisinsight:
    container_name: shop_redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
