version: '3'

services:
  queue-bus:
    container_name: shop_queue-bus
    ports:
      - 46379:6379
    image: redis:latest
    networks:
      - shop-network

  shop_proxy:
    container_name: shop_proxy
    image: nginx:alpine
    ports:
      - 4080:80
    depends_on:
      - shop_back
    volumes:
     - ./docker-resources/nginx:/etc/nginx/conf.d
     - ./shop_back/dist/public:/app/public
    networks:
      - shop-network
      - shop-network-external

  shop_back:
    build: ./shop_back
    container_name: shop_back
    depends_on:
      - shop_migrations
    networks:
      - shop-network

  shop_elasticsearch:
    container_name: shop_elasticsearch
    restart: unless-stopped
    image: elasticsearch:8.5.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    volumes:
      - ./docker-resources/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - shop-network

  redis:
    container_name: shop_redis
    image: redis:latest
    networks:
      - shop-network

  shop_migrations:
    container_name: shop_migrations
    command: 'php bin/console --no-interaction doctrine:migrations:migrate'
    build: ./shop_back
    networks:
      - shop-network

  queue-consumer:
    build: ./shop_back
    container_name: shop_queue-consumer
    command: 'php bin/console messenger:consume async -vv'
    depends_on:
      - shop_migrations
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

  shop-network-external:
    external: true
