version: '3'

services:
  shop_proxy:
    image: nginx:alpine
    depends_on:
      - shop_back
    volumes:
     - ./docker-resources/nginx:/etc/nginx/conf.d
     - ./shop_back/app:/app/code

  shop_back:
    image: webdevops/php:7.4-alpine
    volumes:
     - ./shop_back/app:/app/code
