version: '3'

services:
  shop_proxy:
    image: nginx:alpine
    depends_on:
      - shop_back
    volumes:
     - ./docker-resources/nginx:/etc/nginx/conf.d
     - ./shop_back/app:/app/code

  shop_back:
    image: webdevops/php:7.4-alpine
    volumes:
     - ./shop_back/app:/app/code

  shop_elasticsearch:
    container_name: shop_elasticsearch
    image: elasticsearch:8.5.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      # - ES_JAVA_OPTS=-Xms512m -Xmx512m
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    ports:
      - 9200:9200
    volumes:
      - ./docker-resources/elasticsearch/data:/usr/share/elasticsearch/data

  shop_redis:
    container_name: shop_redis
    image: redis:latest

  # shop_kibana:
  #   container_name: shop_kibana
  #   image: kibana:8.5.2
  #   ports:
  #     - 5601:5601
