version: '3'

services:
  queue-bus:
    container_name: shop_queue-bus
    ports:
      - 46379:6379
    image: redis:latest
    networks:
      - shop-network

  shop_proxy:
    container_name: shop_proxy
    image: nginx:alpine
    ports:
      - 4080:80
    depends_on:
      - shop_back
    volumes:
     - ./docker-resources/nginx:/etc/nginx/conf.d
     - shop-back-app-vol:/app
    networks:
      - shop-network
      - shop-network-external

  shop_back:
    image: webdevops/php:7.4-alpine
    container_name: shop_back
    volumes:
      - shop-back-app-vol:/app
    depends_on:
      - shop_migrations
    networks:
      - shop-network

  redis:
    container_name: shop_redis
    image: redis:latest
    networks:
      - shop-network

  queue-consumer_async:
    image: webdevops/php:7.4-alpine
    container_name: shop_queue-consumer_async
    command: 'php /app/bin/console messenger:consume async -vv'
    restart: unless-stopped
    volumes:
      - shop-back-app-vol:/app
    depends_on:
      - shop_migrations
    networks:
      - shop-network

  queue-consumer_parsing:
    image: webdevops/php:7.4-alpine
    container_name: shop_queue-consumer_parsing
    command: 'php /app/bin/console messenger:consume parsing -vv'
    restart: unless-stopped
    volumes:
      - shop-back-app-vol:/app
    depends_on:
      - shop_migrations
    networks:
      - shop-network

  shop_migrations:
    image: webdevops/php:7.4-alpine
    container_name: shop_migrations
    command: 'php /app/bin/console --no-interaction doctrine:migrations:migrate'
    depends_on:
      - back-app-builder
    volumes:
      - shop-back-app-vol:/app
    networks:
      - shop-network

  back-app-builder:
    build: ./shop_back
    container_name: shop_back-app-builder
    restart: unless-stopped
    volumes:
      - shop-back-app-vol:/app
    networks:
      - shop-network

volumes:
  shop-back-app-vol:

networks:
  shop-network:
    driver: bridge

  shop-network-external:
    external: true
