version: '3.9'

services:
  shop_redisinsight:
    container_name: shop_redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    networks:
      - shop-network

  syncer:
    build:
      context: ./syncer
    container_name: shop_back_app_syncer
    command: '/root/sync.sh'
    volumes:
      - ./shop_back/dist:/tmp/app_source
      - shop-back-app-vol:/tmp/app
    depends_on:
      - back-app-builder

  shop_back:
    image: webdevops/php-dev:7.4-alpine
    ports:
      - 49003:9003
    environment:
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=PHP_IDE_CONFIG
    networks:
      - local-db-network

  queue-consumer_async:
    networks:
      - local-db-network

  queue-consumer_parsing:
    networks:
      - local-db-network

  shop_migrations:
    networks:
      - local-db-network

  back-app-builder:
    networks:
      - local-db-network

networks:
  local-db-network:
    name: local-db-network
    external: true
